# Generated by Django 5.0.7 on 2024-08-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='id',
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='crew',
            name='agents',
        ),
        migrations.AlterField(
            model_name='crew',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='crew',
            name='agents',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
