# Generated by Django 5.0.7 on 2024-08-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_edge_target_alter_edge_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='relation_type',
            field=models.CharField(default=[], max_length=30),
            preserve_default=False,
        ),
    ]
