# Generated by Django 5.0.7 on 2024-08-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_edge_relation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('links', models.CharField(max_length=1000)),
            ],
        ),
    ]
