# Generated by Django 5.0.7 on 2024-08-16 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_contextbin'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edge',
            name='source',
        ),
        migrations.AddField(
            model_name='edge',
            name='source_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='edge',
            name='source_object_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
