# Generated by Django 5.0.7 on 2024-08-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_alter_edge_source_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('task_time', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
