# Generated by Django 5.0.7 on 2024-08-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_remove_edge_target_edge_target_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
