# Generated by Django 5.0.7 on 2024-08-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_agent_id_alter_agent_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='id',
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
