# Generated by Django 5.0.7 on 2024-08-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_agent_id_alter_agent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(default=[], max_length=30),
            preserve_default=False,
        ),
    ]
