# Generated by Django 5.0.7 on 2024-08-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0016_agent_agent_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='input_format',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='output_format',
        ),
        migrations.AddField(
            model_name='task',
            name='input_format',
            field=models.CharField(default=[], max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='output_format',
            field=models.CharField(default=[], max_length=30),
            preserve_default=False,
        ),
    ]
