# Generated by Django 5.0.7 on 2024-08-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0017_remove_agent_input_format_remove_agent_output_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextbin',
            name='text',
            field=models.CharField(default=[], max_length=700000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='backstory',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='agent',
            name='goal',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(max_length=1000),
        ),
    ]
