# Generated by Django 5.1.5 on 2025-03-22 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='papers/')),
                ('file_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeamLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kb_path', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kb_path', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(max_length=100)),
                ('expertise', models.CharField(max_length=100)),
                ('knowledge', models.CharField(max_length=150)),
                ('stored_papers', models.ManyToManyField(related_name='agents', to='core.paper')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date', models.DateTimeField()),
                ('task', models.CharField(max_length=1000)),
                ('expectations', models.CharField(max_length=1000)),
                ('cycles', models.IntegerField()),
                ('report_guidelines', models.CharField(max_length=1000)),
                ('method', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('engine', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('output', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('chat_log', models.FileField(blank=True, null=True, upload_to='report_logs/')),
                ('chosen_team', models.ManyToManyField(related_name='reports_chosen_agents', to='core.agent')),
                ('context', models.ManyToManyField(related_name='reports', to='core.paper')),
                ('potential_agents', models.ManyToManyField(related_name='reports_p_agents', to='core.agent')),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='core.teamlead')),
            ],
        ),
    ]
