# Generated by Django 5.1.5 on 2025-03-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teamlead',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
