# Generated by Django 5.0.7 on 2024-09-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationLog',
            fields=[
                ('date', models.DateTimeField()),
                ('topic_id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('log_text', models.CharField(max_length=100000000)),
                ('engine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StoredPapers',
            fields=[
                ('doi', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('authors', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('date_accessed', models.DateTimeField()),
            ],
        ),
    ]
