# Generated by Django 5.0.7 on 2024-09-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue_display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationlog',
            name='agents',
            field=models.CharField(default='', max_length=1000000000),
            preserve_default=False,
        ),
    ]
