# Generated by Django 5.0.7 on 2024-09-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue_display', '0002_conversationlog_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationlog',
            name='topic_text',
            field=models.CharField(default='', max_length=1000000000),
            preserve_default=False,
        ),
    ]
