# Generated by Django 5.0.7 on 2024-09-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue_display', '0003_conversationlog_topic_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationlog',
            name='title',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
